// Every payment that is NOT a client receipt, in one shape so one table can
// list them and one pair of functions can correct or cancel them.
//
// Each of these is really two things: the entry against the party (a payment on
// a purchase, on a factory's making charges, an expense record) and the matching
// movement in the account it came out of. Correcting one without the other is
// how a locker balance and a supplier's due drift apart, so both sides move
// together here or neither does.
//
// Client receipts are deliberately NOT here — they allocate across a client's
// orders and have their own engine (src/lib/receipts.ts).
import { updateDb, type DB, type Expense, type LockerTransaction } from "./db";

export type EntryKind = "supplier" | "factory" | "expense" | "locker";

export interface MoneyEntry {
  id: string;             // the payment/expense/transaction id
  kind: EntryKind;
  date: string;
  party: string;          // supplier / factory / expense title / locker category
  against?: string;       // which bill it settles — invoice #, order #, category
  amount: number;         // in `currency`
  currency: "INR" | "USD";
  lockerId?: string;
  note?: string;
  direction: "in" | "out";
  /** False when this row can't be safely corrected from here, with the reason. */
  locked?: string;
}

const r2 = (n: number) => Math.round(n * 100) / 100;

/** The account movement that belongs to one entry. Newer rows carry `paymentId`;
 *  older ones are matched on account + amount + the second they were written. */
function pairedTxn(db: DB, entryId: string, at: string, lockerId?: string, amount?: number) {
  const txns = db.lockerTransactions ?? [];
  return txns.find(t => t.paymentId === entryId)
    ?? txns.find(t =>
      !t.paymentId && t.lockerId === lockerId && Math.abs(t.amountInr - (amount ?? 0)) < 0.01
      && Math.abs(+new Date(t.createdAt) - +new Date(at)) < 1500);
}

export function listEntries(db: DB, kind: EntryKind): MoneyEntry[] {
  const out: MoneyEntry[] = [];

  if (kind === "supplier") {
    for (const p of db.purchases ?? []) {
      const supplier = db.suppliers.find(s => s.id === p.supplierId);
      for (const pay of p.payments ?? []) {
        out.push({
          id: pay.id, kind, date: pay.createdAt,
          party: supplier?.name ?? "Supplier",
          against: p.invoiceNumber ? `Invoice ${p.invoiceNumber}` : `Purchase ${p.id.slice(-6)}`,
          amount: pay.amountInr, currency: "INR",
          lockerId: pay.lockerId, note: pay.note, direction: "out",
        });
      }
    }
    for (const r of db.supplierReceipts ?? []) {
      const supplier = db.suppliers.find(s => s.id === r.supplierId);
      out.push({
        id: r.id, kind, date: r.createdAt,
        party: supplier?.name ?? "Supplier", against: "Refund / return",
        amount: r.amountInr, currency: "INR",
        lockerId: r.lockerId, note: r.note, direction: "in",
      });
    }
  }

  if (kind === "factory") {
    for (const mi of db.materialIssuances ?? []) {
      const factory = db.factories.find(f => f.id === mi.factoryId);
      const order = db.orders.find(o => o.id === mi.orderId);
      for (const pay of mi.makingCharges?.payments ?? []) {
        out.push({
          id: pay.id, kind, date: pay.createdAt,
          party: factory?.name ?? "Factory",
          against: order ? `Order ${order.orderNumber}` : "Making charges",
          amount: pay.amountInr, currency: "INR",
          lockerId: pay.lockerId, note: pay.note, direction: "out",
        });
      }
    }
  }

  if (kind === "expense") {
    for (const e of db.expenses ?? []) {
      const paidTo = e.paidToEmployeeId ? db.users.find(u => u.id === e.paidToEmployeeId) : undefined;
      out.push({
        id: e.id, kind, date: e.createdAt,
        party: e.title,
        against: paidTo ? `${e.category} · ${paidTo.name}` : e.category,
        amount: e.amount, currency: (e.currency || "INR") as "INR" | "USD",
        lockerId: e.lockerId, note: e.note, direction: "out",
      });
    }
  }

  if (kind === "locker") {
    for (const t of db.lockerTransactions ?? []) {
      // Anything generated by another entry is corrected from ITS row, not here —
      // editing the movement alone would leave the bill it paid untouched.
      const fromElsewhere = t.refType && t.refType !== "manual";
      out.push({
        id: t.id, kind, date: t.createdAt,
        party: db.lockers.find(l => l.id === t.lockerId)?.name ?? "Account",
        against: t.category ?? t.type,
        amount: t.amountInr, currency: (t.currency || "INR") as "INR" | "USD",
        lockerId: t.lockerId, note: t.note,
        direction: t.type === "income" || t.type === "transfer_in" ? "in" : "out",
        locked: fromElsewhere
          ? "Created by another entry — correct it where it was recorded"
          : (t.pairedLockerId ? "Part of a transfer — cancel it from the transfer" : undefined),
      });
    }
  }

  // A payment made "oldest bill first" can be split across several bills while
  // the account shows ONE movement for the lot. There is no way to correct one
  // of those halves without either leaving the account wrong or removing a
  // movement that belongs to the others, so those rows are read-only and say so.
  for (const e of out) {
    if (e.locked || !e.lockerId) continue;
    if (!pairedTxn(db, e.id, e.date, e.lockerId, e.amount)) {
      e.locked = "Paid across several bills in one go — correct it from the account ledger";
    }
  }


  return out.sort((a, b) => +new Date(b.date) - +new Date(a.date));
}

export interface EntryPatch {
  amount?: number;
  date?: string;
  note?: string;
  lockerId?: string;
  userId: string;
}

/** Move the paired account movement along with the entry it belongs to. */
function syncTxn(d: DB, entry: MoneyEntry, patch: EntryPatch) {
  const txn = pairedTxn(d, entry.id, entry.date, entry.lockerId, entry.amount);
  // Never create one here. An entry with no movement of its own shares a
  // combined one, and adding a second would count the same money twice —
  // listEntries() locks those rows so this cannot be reached for them.
  if (!txn) return;

  const live = (d.lockerTransactions ?? []).find(t => t.id === txn.id);
  if (!live) return;
  if (patch.amount !== undefined) live.amountInr = r2(patch.amount);
  if (patch.date !== undefined) live.createdAt = patch.date;
  if (patch.note !== undefined) live.note = patch.note || undefined;
  if (patch.lockerId !== undefined) {
    live.lockerId = patch.lockerId;
    live.currency = (d.lockers.find(l => l.id === patch.lockerId)?.currency || "INR") as "INR" | "USD";
  }
  live.paymentId = entry.id; // adopt a legacy row so the next edit matches exactly
}

function dropTxn(d: DB, entry: MoneyEntry) {
  const txn = pairedTxn(d, entry.id, entry.date, entry.lockerId, entry.amount);
  if (txn) d.lockerTransactions = (d.lockerTransactions ?? []).filter(t => t.id !== txn.id);
}

/** Correct one entry — the party's books and the account move together. */
export function editEntry(entry: MoneyEntry, patch: EntryPatch): void {
  updateDb(d => {
    if (entry.kind === "supplier") {
      for (const p of d.purchases ?? []) {
        const pay = (p.payments ?? []).find(x => x.id === entry.id);
        if (pay) {
          if (patch.amount !== undefined) pay.amountInr = r2(patch.amount);
          if (patch.date !== undefined) pay.createdAt = patch.date;
          if (patch.note !== undefined) pay.note = patch.note || undefined;
          if (patch.lockerId !== undefined) pay.lockerId = patch.lockerId;
          syncTxn(d, entry, patch);
          return;
        }
      }
      const rec = (d.supplierReceipts ?? []).find(x => x.id === entry.id);
      if (rec) {
        if (patch.amount !== undefined) rec.amountInr = r2(patch.amount);
        if (patch.date !== undefined) rec.createdAt = patch.date;
        if (patch.note !== undefined) rec.note = patch.note || undefined;
        if (patch.lockerId !== undefined) rec.lockerId = patch.lockerId;
        syncTxn(d, entry, patch);
      }
      return;
    }

    if (entry.kind === "factory") {
      for (const mi of d.materialIssuances ?? []) {
        const pay = (mi.makingCharges?.payments ?? []).find(x => x.id === entry.id);
        if (pay) {
          if (patch.amount !== undefined) pay.amountInr = r2(patch.amount);
          if (patch.date !== undefined) pay.createdAt = patch.date;
          if (patch.note !== undefined) pay.note = patch.note || undefined;
          if (patch.lockerId !== undefined) pay.lockerId = patch.lockerId;
          syncTxn(d, entry, patch);
          return;
        }
      }
      return;
    }

    if (entry.kind === "expense") {
      const e = (d.expenses ?? []).find(x => x.id === entry.id) as Expense | undefined;
      if (!e) return;
      if (patch.amount !== undefined) e.amount = r2(patch.amount);
      if (patch.date !== undefined) e.createdAt = patch.date;
      if (patch.note !== undefined) e.note = patch.note || undefined;
      if (patch.lockerId !== undefined) {
        e.lockerId = patch.lockerId;
        // The amount is always in the account's own currency, so moving an
        // expense to an account in another currency changes what it means.
        e.currency = (d.lockers.find(l => l.id === patch.lockerId)?.currency || "INR") as "INR" | "USD";
      }
      syncTxn(d, entry, patch);
      return;
    }

    if (entry.kind === "locker") {
      const t = (d.lockerTransactions ?? []).find(x => x.id === entry.id) as LockerTransaction | undefined;
      if (!t) return;
      if (patch.amount !== undefined) t.amountInr = r2(patch.amount);
      if (patch.date !== undefined) t.createdAt = patch.date;
      if (patch.note !== undefined) t.note = patch.note || undefined;
      if (patch.lockerId !== undefined) {
        t.lockerId = patch.lockerId;
        t.currency = (d.lockers.find(l => l.id === patch.lockerId)?.currency || "INR") as "INR" | "USD";
      }
    }
  });
}

/** In plain words, what cancelling this entry changes — shown before confirming. */
export function entryImpact(entry: MoneyEntry, lockerName?: string): string[] {
  const money = `${entry.currency === "USD" ? "$" : "₹"}${Math.round(entry.amount).toLocaleString("en-IN")}`;
  const out: string[] = [];
  if (entry.kind === "supplier") {
    out.push(entry.direction === "out"
      ? `• ${money} goes back onto ${entry.party}'s dues — that bill will show as unpaid again`
      : `• ${money} is removed from what ${entry.party} refunded`);
  }
  if (entry.kind === "factory") out.push(`• ${money} goes back onto ${entry.party}'s making charges`);
  if (entry.kind === "expense") out.push(`• the expense is removed from the books and every expense report`);
  if (entry.kind === "locker") out.push(`• the entry is removed from the account ledger`);
  if (lockerName) {
    out.push(entry.direction === "out"
      ? `• ${lockerName} goes back up by ${money}`
      : `• ${lockerName} goes down by ${money}`);
  }
  out.push("• nothing else changes — every other payment stays exactly as it is");
  return out;
}

/** Cancel one entry: the party's books and the account both come back. */
export function deleteEntry(entry: MoneyEntry): void {
  updateDb(d => {
    if (entry.kind === "supplier") {
      for (const p of d.purchases ?? []) {
        if ((p.payments ?? []).some(x => x.id === entry.id)) {
          p.payments = p.payments.filter(x => x.id !== entry.id);
          dropTxn(d, entry);
          return;
        }
      }
      if ((d.supplierReceipts ?? []).some(x => x.id === entry.id)) {
        d.supplierReceipts = d.supplierReceipts.filter(x => x.id !== entry.id);
        dropTxn(d, entry);
      }
      return;
    }
    if (entry.kind === "factory") {
      for (const mi of d.materialIssuances ?? []) {
        if ((mi.makingCharges?.payments ?? []).some(x => x.id === entry.id)) {
          mi.makingCharges.payments = mi.makingCharges.payments.filter(x => x.id !== entry.id);
          dropTxn(d, entry);
          return;
        }
      }
      return;
    }
    if (entry.kind === "expense") {
      d.expenses = (d.expenses ?? []).filter(x => x.id !== entry.id);
      dropTxn(d, entry);
      return;
    }
    if (entry.kind === "locker") {
      d.lockerTransactions = (d.lockerTransactions ?? []).filter(x => x.id !== entry.id);
    }
  });
}
